using ATBasketRobotServer.Application.Messaging;
namespace ATBasketRobotServer.Application.Features.CompanyFeatures.ReportFeatures.Queries.TopCustomerOrderedSalesContent.TopCustomerOrderedSalesContentMonth;
//public sealed record GetTopCustomerOrderedSalesContentMonthQuery(string companyId, string customerId) : IQuery<GetTopCustomerOrderedSalesContentMonthQueryResponse>;