using ATBasketRobotServer.Application.Messaging;
namespace ATBasketRobotServer.Application.Features.CompanyFeatures.ProductFeatures.Commands.CreateProductAll;
public sealed record CreateProductAllCommand : ICommand<CreateProductAllCommandResponse>;