using ATBasketRobotServer.Application.Messaging;
namespace ATBasketRobotServer.Application.Features.AppFeatures.MainRoleAndUserRLFeatures.Commands.CreateMainRoleAndUserRL;
public sealed record CreateMainRoleAndUserRLCommand(string UserId, string MainRoleId) : ICommand<CreateMainRoleAndUserRLCommandResponse>;