using ATBasketRobotServer.Application.Messaging;
namespace ATBasketRobotServer.Application.Features.CompanyFeatures.ProductCustomerBlockFeatures.Commands.CreateProductCustomerBlock;
public sealed record CreateProductCustomerBlockCommand(string productid, string customerid, string companyId) : ICommand<CreateProductCustomerBlockCommandResponse>;