using ATBasketRobotServer.Domain.Dtos.Report;
namespace ATBasketRobotServer.Application.Features.CompanyFeatures.ReportFeatures.Queries.OrderedOffers.GetOrderedOffersWeek;
public sealed record GetOrderedOffersWeekQueryResponse(IList<OrderedOffersWeekDto> data);