using ATBasketRobotServer.Domain.CompanyEntities;
using ATBasketRobotServer.Domain.Repositories.GenericRepositories.CompanyDbContext;
namespace ATBasketRobotServer.Domain.Repositories.CompanyDbContext.ProductCampaignRepositories;
public interface IProductCampaignCommandRepository : ICompanyDbCommandRepository<ProductCampaign>
{
}