using ATBasketRobotServer.Domain.Dtos.Report;
namespace ATBasketRobotServer.Application.Features.CompanyFeatures.ReportFeatures.Queries.OfferedOrderProduct.GetOfferedOrderProductDay;
public sealed record GetOfferedOrderProductDayQueryResponse(IList<OrderedProductDayDto> data);