using ATBasketRobotServer.Application.Messaging;
namespace ATBasketRobotServer.Application.Features.CompanyFeatures.BasketStatusFeatures.Queries.GetAllBasketStatusDto;
public sealed record GetAllBasketStatusDtoQuery(string companyId) : IQuery<GetAllBasketStatusDtoQueryResponse>;