using ATBasketRobotServer.Application.Messaging;
namespace ATBasketRobotServer.Application.Features.CompanyFeatures.ProductCampaignFeatures.Commands.CreateProductCampaignAll;
public sealed record CreateProductCampaignAllCommand : ICommand<CreateProductCampaignAllCommandResponse>;