using ATBasketRobotServer.Application.Messaging;
namespace ATBasketRobotServer.Application.Features.CompanyFeatures.CustomerFeatures.Commands.CreateCustomerAll;
public sealed record CreateCustomerAllCommand : ICommand<CreateCustomerAllCommandResponse>;