using ATBasketRobotServer.Application.Messaging;
namespace ATBasketRobotServer.Application.Features.CompanyFeatures.OfferFeatures.Commands.CreateOfferAll;
public sealed record CreateOfferAllCommand : ICommand<CreateOfferAllCommandResponse>;