using ATBasketRobotServer.Domain.Dtos.Report;
namespace ATBasketRobotServer.Application.Features.CompanyFeatures.ReportFeatures.Queries.OfferedOrderCustomer.GetOfferedOrderCustomerDay;
public sealed record GetOfferedOrderDayQueryResponse(IList<OrderedCustomerDayDto> data);