using ATBasketRobotServer.Domain.Dtos.Report;
namespace ATBasketRobotServer.Application.Features.CompanyFeatures.ReportFeatures.Queries.OrderedOffers.GetOrderedOffersMonth;
public sealed record GetOrderedOffersMonthQueryResponse(IList<OrderedOffersMonthDto> data);