using ATBasketRobotServer.Domain.Dtos.Report;
namespace ATBasketRobotServer.Application.Features.CompanyFeatures.ReportFeatures.Queries.OrderedOffers.GetOrderedOffersYear;
public sealed record GetOrderedOffersYearQueryResponse(IList<OrderedOffersYearDto> data);