using ATBasketRobotServer.Application.Messaging;
namespace ATBasketRobotServer.Application.Features.CompanyFeatures.BasketStatusFeatures.Commands.RemoveByIdBasketStatus;
public sealed record RemoveByIdBasketStatusCommand(string Id, string companyId) : ICommand<RemoveByIdBasketStatusCommandResponse>;