using ATBasketRobotServer.Application.Messaging;
namespace ATBasketRobotServer.Application.Features.CompanyFeatures.BasketStatusFeatures.Commands.CreateBasketStatusAll;
public sealed record CreateBasketStatusAllCommand : ICommand<CreateBasketStatusAllCommandResponse>;