using ATBasketRobotServer.Application.Messaging;

namespace ATBasketRobotServer.Application.Features.CompanyFeatures.ReportFeatures.Queries.CustomerOfferedOrderCounts.GetCustomerOfferedOrderCounts;

public sealed record GetCustomerOfferedOrderCountsQuery(string companyId) : IQuery<GetCustomerOfferedOrderCountsQueryResponse>;